### ISSUE TITLE
Broken UX and conceptual error. Marketplace. Special Deals.

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-io#30]
> <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/184664227/63aef646087bdac06dd60ec8/D97B2263-B78C-44C0-88EF-89EB7D757A7E.jpeg"></div>
By clicking on Active deals from CPU coin it brings me to Active deals where CPUcoin is.... a broken loop

**Link:** [Conversation with demo-caesar@holdex.io](https://app.intercom.com/a/apps/d1yuld8c/respond/inbox/all/conversations/25759874884)

**Customer:** [demo-caesar@holdex.io](https://app.intercom.com/a/apps/d1yuld8c/users/5e32050c5e038e8f87701fac/all-conversations) from [Holdex](https://app.intercom.com/a/apps/d1yuld8c/companies/5e32c5c2f8568b46397c66f9)
**Customer ID:** 51b134b1-ef97-4280-86f9-64c26565bb4e
**Company ID:** 5e32c5c2f8568b46397c66fa-qualification-company
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/d1yuld8c/respond/inbox/all/conversations/25759874884) when this issue is closed.

**Comment by markholdex** [comment]
@zolotokrylin You probably didn't update the page. The already interface had a different look when I checked for the issue.
