### ISSUE TITLE
Add Isaac Mao as advisor

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-io#6]
Acceptance Criteria: 

- [x] Add Isaac after Adam
- [x] Remove LinkedIn linked from all Developers profiles (keep Marks's)
- [x] Put advisers on a separate line (visually group them)
- [x] Change address of HK office to `WeWork, 2F, 40-44 Bonham Strand, Sheung Wan, Hong Kong` (including map)
- [x] Replace [Giorgia's picture](https://drive.google.com/open?id=1f7xhTILwTSyiJPUtM0G-UhkaRnNKgyrz)
- [x] Add Nick after George
- [x] Add Iaroslav after Nick
- [x] Change Giorgia's photo & position to `COO`
- [x] Change Vadim's position to `CEO` (remove `CTO`)

**Comment by El3n** [comment]
@zolotokrylin This issue is not added on the development board, can i move it in To Do section?
